name: Scheduled Email Sender

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual run

jobs:
  run-email-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run email scheduler
        run: node sendScheduler.cjs

        # Optional: if you need .env variables from GitHub Secrets
      - name: Export API key
        run: echo "BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}" >> .env
